/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
	"tandoor adapter settings": {
		en: "Adapter settings for tandoor",
		de: "Adaptereinstellungen für tandoor",
		ru: "Настройки адаптера для tandoor",
		pt: "Configurações do adaptador para tandoor",
		nl: "Adapterinstellingen voor tandoor",
		fr: "Paramètres d'adaptateur pour tandoor",
		it: "Impostazioni dell'adattatore per tandoor",
		es: "Ajustes del adaptador para tandoor",
		pl: "Ustawienia adaptera dla tandoor",
		"zh-cn": "tandoor的适配器设置",
	},
	host: {
		en: "Address or IP",
		de: "Address or IP",
		ru: "Address or IP",
		pt: "Address or IP",
		nl: "Address or IP",
		fr: "Address or IP",
		it: "Address or IP",
		es: "Address or IP",
		pl: "Address or IP",
		"zh-cn": "Address or IP",
	},
	port: {
		en: "Port",
		de: "Port",
		ru: "Port",
		pt: "Port",
		nl: "Port",
		fr: "Port",
		it: "Port",
		es: "Port",
		pl: "Port",
		"zh-cn": "Port",
	},
	token: {
		en: "API-token",
		de: "API-token",
		ru: "API-token",
		pt: "API-token",
		nl: "API-token",
		fr: "API-token",
		it: "API-token",
		es: "API-token",
		pl: "API-token",
		"zh-cn": "API-token",
	},
};
